#!/bin/bash

echo "🎨 Deploying to Render..."
echo "============================================================"
echo ""
echo "📋 Manual Deployment Steps:"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New' → 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Configure the service:"
echo "   - Name: gas-station-reco"
echo "   - Environment: Python"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: gunicorn web_app:app"
echo "6. Add environment variables:"
echo "   - GOOGLE_MAPS_API_KEY: AIzaSyDjNxcwyJWryuErYs9dD6VPuyqPKmFgjjk"
echo "   - CLAUDE_API_KEY: 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"
echo "7. Click 'Create Web Service'"
echo ""
echo "🌐 Your app will be available at: https://gas-station-reco.onrender.com"
echo ""
echo "📊 Monitor your app at: https://dashboard.render.com" 